set_property IOSTANDARD LVCMOS33 [get_ports {q[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clr1]
set_property IOSTANDARD LVCMOS33 [get_ports clr2]
set_property IOSTANDARD LVCMOS33 [get_ports ld]
set_property IOSTANDARD LVCMOS33 [get_ports m]
set_property PACKAGE_PIN R2 [get_ports {q[4]}]
set_property PACKAGE_PIN T1 [get_ports {q[3]}]
set_property PACKAGE_PIN U1 [get_ports {q[2]}]
set_property PACKAGE_PIN W2 [get_ports {q[1]}]
set_property PACKAGE_PIN R3 [get_ports {q[0]}]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN T2 [get_ports clr1]
set_property PACKAGE_PIN T3 [get_ports clr2]
set_property PACKAGE_PIN L1 [get_ports m]
set_property PACKAGE_PIN P1 [get_ports {s[4]}]
set_property PACKAGE_PIN N3 [get_ports {s[3]}]
set_property PACKAGE_PIN P3 [get_ports {s[2]}]
set_property PACKAGE_PIN U3 [get_ports {s[1]}]
set_property PACKAGE_PIN W3 [get_ports {s[0]}]

set_property PACKAGE_PIN W13 [get_ports ld]

set_property IOSTANDARD LVCMOS33 [get_ports f]
set_property PACKAGE_PIN V3 [get_ports f]

set_property PACKAGE_PIN V2 [get_ports en]
set_property IOSTANDARD LVCMOS33 [get_ports en]
